version: "3.7"

services:
  nginx_frontend:
    image: nginx-reverse-proxy
    ports:
      - "300:300"
    networks:
      - traffic_test
  nginx_backend:
    image: nginx-100-200
    ports:
      - "7080:80"
      - "7100:100"
      - "7200:200"
    networks:
      - traffic_test

networks:
  traffic_test:
    driver: overlay
